### PR TITLE
Fix "Error: crypto.getRandomValues must be defined" on Expo App

### PR DESCRIPTION
**Pull request by Ariflo**

### CODE REVIEW

**Comment by Ethella** [comment]
Is the dependency required for the SDK? or just the app?

**Comment by Ariflo** [comment]
> Is the dependency required for the SDK? or just the app?
Good question, let me review the exact error I saw and see if it makes sense to do that, iirc this is specific to Expo 49. 🤔

**Comment by Ethella** [comment]
In that case, we might need to that as a peer dependency or even subdependency

**Comment by Ariflo** [comment]
> Is the dependency required for the SDK? or just the app?

@Ethella Looks like this error occurs when we try to use any of the `web3` related methods and was introduced with this change https://github.com/magiclabs/react-native-demo/pull/59 from dependabot (ie. web3 from v1.8.1 to v4.0.3).

LMK your thoughts here; I'm now less inclined to make any changes to our SDK's peer dependencies, but perhaps this deserves a call out on the README / Magic docs?

**Comment by Ethella** [comment]
> LMK your thoughts here; I'm now less inclined to make any changes to our SDK's peer dependencies, but perhaps this deserves a call out on the README / Magic docs?

Yes, it will be a manual process that needs to be documented here
https://magic.link/docs/auth/login-methods/email/integration/react-native#set-up-web-3-js

**Comment by Ariflo** [comment]
> Yes, it will be a manual process that needs to be documented here

Cool, can I haz ✅ :)

**Review by Ethella — APPROVED** [review]

**Pull request merged**
